//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Demo.UnitTest.BizArticleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", ConfigurationName="BizArticleService.ArticleService")]
    public interface ArticleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="UploadDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ben.Demo.UnitTest.BizArticleService.UploadDocumentResponse UploadDocument(Ben.Demo.UnitTest.BizArticleService.UploadDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="UploadDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.UploadDocumentResponse> UploadDocumentAsync(Ben.Demo.UnitTest.BizArticleService.UploadDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DownloadDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ben.Demo.UnitTest.BizArticleService.DownloadDocumentResponse DownloadDocument(Ben.Demo.UnitTest.BizArticleService.DownloadDocumentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="DownloadDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.DownloadDocumentResponse> DownloadDocumentAsync(Ben.Demo.UnitTest.BizArticleService.DownloadDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle")]
    public partial class BizArticles : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BizArticlesBizArticle bizArticleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BizArticlesBizArticle BizArticle {
            get {
                return this.bizArticleField;
            }
            set {
                this.bizArticleField = value;
                this.RaisePropertyChanged("BizArticle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle")]
    public partial class BizArticlesBizArticle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bizArticleNameField;
        
        private byte[] bizArticleContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BizArticleName {
            get {
                return this.bizArticleNameField;
            }
            set {
                this.bizArticleNameField = value;
                this.RaisePropertyChanged("BizArticleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] BizArticleContent {
            get {
                return this.bizArticleContentField;
            }
            set {
                this.bizArticleContentField = value;
                this.RaisePropertyChanged("BizArticleContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles;
        
        public UploadDocumentRequest() {
        }
        
        public UploadDocumentRequest(Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles;
        
        public UploadDocumentResponse() {
        }
        
        public UploadDocumentResponse(Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles;
        
        public DownloadDocumentRequest() {
        }
        
        public DownloadDocumentRequest(Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles;
        
        public DownloadDocumentResponse() {
        }
        
        public DownloadDocumentResponse(Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArticleServiceChannel : Ben.Demo.UnitTest.BizArticleService.ArticleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArticleServiceClient : System.ServiceModel.ClientBase<Ben.Demo.UnitTest.BizArticleService.ArticleService>, Ben.Demo.UnitTest.BizArticleService.ArticleService {
        
        public ArticleServiceClient() {
        }
        
        public ArticleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArticleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArticleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ben.Demo.UnitTest.BizArticleService.UploadDocumentResponse Ben.Demo.UnitTest.BizArticleService.ArticleService.UploadDocument(Ben.Demo.UnitTest.BizArticleService.UploadDocumentRequest request) {
            return base.Channel.UploadDocument(request);
        }
        
        public void UploadDocument(ref Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles) {
            Ben.Demo.UnitTest.BizArticleService.UploadDocumentRequest inValue = new Ben.Demo.UnitTest.BizArticleService.UploadDocumentRequest();
            inValue.BizArticles = BizArticles;
            Ben.Demo.UnitTest.BizArticleService.UploadDocumentResponse retVal = ((Ben.Demo.UnitTest.BizArticleService.ArticleService)(this)).UploadDocument(inValue);
            BizArticles = retVal.BizArticles;
        }
        
        public System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.UploadDocumentResponse> UploadDocumentAsync(Ben.Demo.UnitTest.BizArticleService.UploadDocumentRequest request) {
            return base.Channel.UploadDocumentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ben.Demo.UnitTest.BizArticleService.DownloadDocumentResponse Ben.Demo.UnitTest.BizArticleService.ArticleService.DownloadDocument(Ben.Demo.UnitTest.BizArticleService.DownloadDocumentRequest request) {
            return base.Channel.DownloadDocument(request);
        }
        
        public void DownloadDocument(ref Ben.Demo.UnitTest.BizArticleService.BizArticles BizArticles) {
            Ben.Demo.UnitTest.BizArticleService.DownloadDocumentRequest inValue = new Ben.Demo.UnitTest.BizArticleService.DownloadDocumentRequest();
            inValue.BizArticles = BizArticles;
            Ben.Demo.UnitTest.BizArticleService.DownloadDocumentResponse retVal = ((Ben.Demo.UnitTest.BizArticleService.ArticleService)(this)).DownloadDocument(inValue);
            BizArticles = retVal.BizArticles;
        }
        
        public System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.DownloadDocumentResponse> DownloadDocumentAsync(Ben.Demo.UnitTest.BizArticleService.DownloadDocumentRequest request) {
            return base.Channel.DownloadDocumentAsync(request);
        }
    }
}
