//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ben.Demo.UnitTest.BizArticleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", ConfigurationName="BizArticleService.BizArticleService")]
    public interface BizArticleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Upload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ben.Demo.UnitTest.BizArticleService.UploadResponse Upload(Ben.Demo.UnitTest.BizArticleService.UploadRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="Upload", ReplyAction="*")]
        System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.UploadResponse> UploadAsync(Ben.Demo.UnitTest.BizArticleService.UploadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Download", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Ben.Demo.UnitTest.BizArticleService.DownloadResponse Download(Ben.Demo.UnitTest.BizArticleService.DownloadRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="Download", ReplyAction="*")]
        System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.DownloadResponse> DownloadAsync(Ben.Demo.UnitTest.BizArticleService.DownloadRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle")]
    public partial class BizArticlesArticle : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string articleNameField;
        
        private byte[] articleContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ArticleName {
            get {
                return this.articleNameField;
            }
            set {
                this.articleNameField = value;
                this.RaisePropertyChanged("ArticleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] ArticleContent {
            get {
                return this.articleContentField;
            }
            set {
                this.articleContentField = value;
                this.RaisePropertyChanged("ArticleContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Article", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles;
        
        public UploadRequest() {
        }
        
        public UploadRequest(Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Article", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles;
        
        public UploadResponse() {
        }
        
        public UploadResponse(Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Article", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles;
        
        public DownloadRequest() {
        }
        
        public DownloadRequest(Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ben.Demo.BizTalk.Schemas.BizArticle", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Article", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles;
        
        public DownloadResponse() {
        }
        
        public DownloadResponse(Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles) {
            this.BizArticles = BizArticles;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BizArticleServiceChannel : Ben.Demo.UnitTest.BizArticleService.BizArticleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BizArticleServiceClient : System.ServiceModel.ClientBase<Ben.Demo.UnitTest.BizArticleService.BizArticleService>, Ben.Demo.UnitTest.BizArticleService.BizArticleService {
        
        public BizArticleServiceClient() {
        }
        
        public BizArticleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BizArticleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizArticleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BizArticleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ben.Demo.UnitTest.BizArticleService.UploadResponse Ben.Demo.UnitTest.BizArticleService.BizArticleService.Upload(Ben.Demo.UnitTest.BizArticleService.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public void Upload(ref Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles) {
            Ben.Demo.UnitTest.BizArticleService.UploadRequest inValue = new Ben.Demo.UnitTest.BizArticleService.UploadRequest();
            inValue.BizArticles = BizArticles;
            Ben.Demo.UnitTest.BizArticleService.UploadResponse retVal = ((Ben.Demo.UnitTest.BizArticleService.BizArticleService)(this)).Upload(inValue);
            BizArticles = retVal.BizArticles;
        }
        
        public System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.UploadResponse> UploadAsync(Ben.Demo.UnitTest.BizArticleService.UploadRequest request) {
            return base.Channel.UploadAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ben.Demo.UnitTest.BizArticleService.DownloadResponse Ben.Demo.UnitTest.BizArticleService.BizArticleService.Download(Ben.Demo.UnitTest.BizArticleService.DownloadRequest request) {
            return base.Channel.Download(request);
        }
        
        public void Download(ref Ben.Demo.UnitTest.BizArticleService.BizArticlesArticle[] BizArticles) {
            Ben.Demo.UnitTest.BizArticleService.DownloadRequest inValue = new Ben.Demo.UnitTest.BizArticleService.DownloadRequest();
            inValue.BizArticles = BizArticles;
            Ben.Demo.UnitTest.BizArticleService.DownloadResponse retVal = ((Ben.Demo.UnitTest.BizArticleService.BizArticleService)(this)).Download(inValue);
            BizArticles = retVal.BizArticles;
        }
        
        public System.Threading.Tasks.Task<Ben.Demo.UnitTest.BizArticleService.DownloadResponse> DownloadAsync(Ben.Demo.UnitTest.BizArticleService.DownloadRequest request) {
            return base.Channel.DownloadAsync(request);
        }
    }
}
